/** @type {import('next').NextConfig} */
const nextConfig = {
    env: {
      NEXT_PUBLIC_AXIOS_URL: process.env.NEXT_PUBLIC_AXIOS_URL,
      NEXT_PUBLIC_PRIMARY_BG_COLOR: process.env.NEXT_PUBLIC_PRIMARY_BG_COLOR,
      NEXT_PUBLIC_PRIMARY_FONT_COLOR: process.env.NEXT_PUBLIC_PRIMARY_FONT_COLOR,
      NEXT_PUBLIC_USER_BG_COLOR: process.env.NEXT_PUBLIC_USER_BG_COLOR,
      NEXT_PUBLIC_ASSISTANT_BG_COLOR: process.env.NEXT_PUBLIC_ASSISTANT_BG_COLOR,
      NEXT_PUBLIC_BACKGROUND_IMAGE: process.env.NEXT_PUBLIC_BACKGROUND_IMAGE,
      NEXT_PUBLIC_AVATAR_IMAGE: process.env.NEXT_PUBLIC_AVATAR_IMAGE,
      NEXT_PUBLIC_PRIMARY_INPUTROW_COLOR: process.env.NEXT_PUBLIC_PRIMARY_INPUTROW_COLOR,
      NEXT_PUBLIC_PRIMARY_SENDBUTTON_COLOR: process.env.NEXT_PUBLIC_PRIMARY_SENDBUTTON_COLOR,
    },
  };
  
  export default nextConfig;