name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_PLANT_0999D740F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/positive-chatbot-app" 
          api_location: "" 
          output_location: "" 
        env:
          NEXT_PUBLIC_AXIOS_URL: ${{ secrets.EPIC_AXIOS_URL }}
          NEXT_PUBLIC_PRIMARY_BG_COLOR: ${{ secrets.EPIC_PRIMARY_BG_COLOR }}
          NEXT_PUBLIC_PRIMARY_FONT_COLOR: ${{ secrets.EPIC_PRIMARY_FONT_COLOR }}
          NEXT_PUBLIC_USER_BG_COLOR: ${{ secrets.EPIC_USER_BG_COLOR }}
          NEXT_PUBLIC_ASSISTANT_BG_COLOR: ${{ secrets.EPIC_ASSISTANT_BG_COLOR }}
          NEXT_PUBLIC_BACKGROUND_IMAGE: ${{ secrets.EPIC_BACKGROUND_IMAGE }}
          NEXT_PUBLIC_AVATAR_IMAGE: ${{ secrets.EPIC_AVATAR_IMAGE }}
          NEXT_PUBLIC_PRIMARY_INPUTROW_COLOR: ${{ secrets.EPIC_PRIMARY_INPUTROW_COLOR }}
          NEXT_PUBLIC_PRIMARY_SENDBUTTON_COLOR: ${{ secrets.EPIC_PRIMARY_SENDBUTTON_COLOR }}
          NEXT_PUBLIC_CUSTOM_LINK_COLOR: ${{ secrets.EPIC_CUSTOM_LINK_COLOR }}
          NEXT_PUBLIC_SHOW_DELETE_ICON: ${{ secrets.EPIC_SHOW_DELETE_ICON }}
          NEXT_PUBLIC_SHOW_ATTACH_FILE_ICON: ${{ secrets.EPIC_SHOW_ATTACH_FILE_ICON }}
          NEXT_PUBLIC_SHOW_SAVE_ICON: ${{ secrets.EPIC_SHOW_SAVE_ICON }}
          NEXT_PUBLIC_SHOW_SUGGEST_QUESTIONS_ICON: ${{ secrets.EPIC_SHOW_SUGGEST_QUESTIONS_ICON }}
          NEXT_PUBLIC_SHOW_AUDIO_RESPONSE_ICON: ${{ secrets.EPIC_SHOW_AUDIO_RESPONSE_ICON }}
          NEXT_PUBLIC_SHOW_FEEDBACK: ${{ secrets.EPIC_SHOW_FEEDBACK }}
          NEXT_PUBLIC_SHOW_VOICE_RECORD_ICON: ${{ secrets.EPIC_SHOW_VOICE_RECORD_ICON }}
          NEXT_PUBLIC_SHOW_INITIAL_QUESTIONS: ${{ secrets.EPIC_SHOW_INITIAL_QUESTIONS }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_PLANT_0999D740F }}
          action: "close"
